export const BOOK_UPDATE = 'BOOK_UPDATE';
export const BOOK_CREATE = 'BOOK_CREATE';
export const BOOKS_FETCH_SUCCESS = 'BOOKS_FETCH_SUCCESS';
export const BOOK_SAVED_SUCCESS = 'BOOK_SAVED_SUCCESS';
export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS';
export const BOOKS_SEARCH_SUCCESS = 'BOOKS_SEARCH_SUCCESS';
export const QUERY_UPDATE = 'QUERY_UPDATE';
export const BOOKS_SEARCH_FAILURE = 'BOOKS_SEARCH_FAILURE';